@startuml GrProcessor
	class GrProcessor {
		+ClassID()
	}

	class GrGeometryProcessor {
		+GrGeometryProcess(ClassID)
		-fVertexAttributes: AttributeSet
		-fInstanceAtrributes: AttributeSet
		-fTextureSamplerCnt: int
	}

	GrGeometryProcessor --|> GrProcessor

	class Attribute {
		-fName: char*
		-fCPUType: GrVertexAttibType
		-fGPUType: SkSLType
		-fOffset: unin32_ty
	}

	class AttributeSet {
		class Iter
		-fAttributes: Attribute*
		-fRawCount: int
		-fCount: int
		-fStride: size_t
	}

	AttributeSet -* Attribute

	class QuadPerEdgeAAGeometryProcessor {
		+name(): char*
		+addToKey()
		+makeProgramImpl(): ProgramImpl 
		-fPosition: Attribute
		-fCoverage: Attribute
		-fColor: Attribute
		-fLocalCoord: Attribute
		-fGeoSubset: Attribute
		-fTexSubset: Attribute
		-fSaturate: Saturate
		-fCoverageMode: CoverageMode
		-fSampler: TextureSampler
	}

	QuadPerEdgeAAGeometryProcessor --|> GrGeometryProcessor
	QuadPerEdgeAAGeometryProcessor -* TextureSampler
	QuadPerEdgeAAGeometryProcessor -* Attribute

	class TextureSampler {
		fSamplerState: GrSamplerState
		fBackendFormat: GrBackendFormat
		fSwizzle: Swizzle
		fIsInitialized: bool
	}

	class GrSamplerState {
		fWrapModes: WrapMode[]
		fFilter: SkFilterMode
		fMipmapMode: SkMipmapMode
		fMaxAniso: int
	}

	TextureSampler -* GrSamplerState
	TextureSampler -* Swizzle

	GrSamplerState -* WrapMode
	GrSamplerState -* SkFilterMode
	GrSamplerState -* SkMipmapMode

	enum WrapMode {
		kClamp
		kRepeat
		kMirrorRepeat
		kClampToBorder
	}

	enum SkFilterMode {
		kNearest
		kLinear
	}

	enum SkMipmapMode {
		KNone
		kNearest
		kLinear
	}

	class Swizzle {
		+applyTo(std::array<float, 4> color): std::array<float, 4> // 颜色rgba顺序交换
		-fKey: uint16_t
	}
@enduml