
@startuml emitAndInstallProcs
class OpsTask {
	+addOp()
	+addDrawOp()
	+canMerge()
	+mergeFrom()
	-fOpChains: OpChain[]
}

OpsTask *- OpChain

class GrRenderTask {
	prePrePare()
	prepare()
	execute()
	#ftarget: GrSurfaceProxy[]
	#addTarget()
}

class OpChain {
	+head()
	+appendOp()
	+prependChain()
	-fList: List<GrOP>
}

class GrOp {
	-fNextInChain
	-fPrevInChain
	+prePrePare()
	+prepare()
	+execute()
	+nextInChain()
	+prevInChain()
}

OpChain *- GrOp

OpsTask --|> GrRenderTask
@enduml
